export const translations = {
  en: {
    goal: "Daily Goal",
    stats: "Stats",
    fail: "Fail",
    pass: "Pass",
    fail_caps: "FAIL",
    pass_caps: "PASS",
    already_know: "I already know this",
    empty_deck: "Empty Deck",
    recall: "Recall",
    recognition: "Recognition",
    mastery: "Mastery",
    tries: "Tries",
    accuracy: "Accuracy",
    streak: "Current Streak",
    syncing_deck: "Syncing Deck...",
    days: "Days",
    back: "Back",
    signout: "Sign Out",
    active_collection: "Active Collection",
    save: "Save",
    ai_add: "AI Add",
    batch_upload: "Batch Upload",
    audio_prefs: "Audio Preferences",
    vocabulary: "Vocabulary",
    mastered: "Mastered",
    struggling: "Struggling",
    by_level: "Vocabulary by Level",
    settings: "Settings",
    close: "Close",
    close_settings: "Close Settings",
    auto_play_jp: "Auto-play Japanese",
    auto_play_en: "Auto-play English",
    starter_collections: "Starter Collections",
    available: "Available",
    audio_desc_jp: "Hear the kanji when card appears",
    audio_desc_en: "Hear translation when flipping",
    process_text: "Process Text",
    format_options: "FORMAT OPTIONS:",
    format_list: "1. List: word, meaning (one per line)",
    format_lyrics: "2. Lyrics: Paste a whole song or text. I'll pick out the new words for you!",
    add_new_word: "Add New Word...",
    success_added: "Successfully added {{count}} words!",
    in_a_row: "in a row",
    loading: "LOADING...",
    loading_session: "Loading Session...",
    daily_goal_met: "Daily Goal Met! 🎉",
    start_journey: "Start your journey by adding some cards.",
    get_started: "+ Get Started",
    how_to_study: "HOW TO STUDY",
    forgot: "Forgot",
    know_it: "Know it!",
    swipe_to_start: "Swipe the card to start",
    word_filters: "Word Filters",
    search_placeholder: "Search kanji, reading, or meaning...",
    app_language: "App Language",
    app_language_desc: "Toggle between English and Japanese",
    kanji_reading: "Kanji / Reading",
    english: "English",
    score: "Score",
    action: "Action",
    add_word_to_block: "Add word to block...",
    added: "Added",
    free: "Free",
    looking_collections: "Looking for new collections...",
    load_more: "Load More",
    remaining: "remaining",
    ai_building: "AI is building your cards...",
    delete: "Delete",
    already_in_deck: "Already in Deck",
    add_to_deck: "Add to Deck +",
    reset_password: "Reset Password",
    create_account: "Create Account",
    welcome_message: "Welcome to FlashKado!",
    email_placeholder: "Email",
    password_placeholder: "Password",
    processing: "Processing...",
    send_reset_link: "Send Reset Link",
    register_button: "Register",
    login_button: "Login",
    or_continue_with: "Or continue with",
    switch_to_login: "Already have an account? Login",
    switch_to_register: "New here? Create an account",
    back_to_login: "Back to Login",
    forgot_password_link: "Forgot your password?",
    check_email_reset: "Check your email for the reset link!",
    check_email_confirm: "Check your email for the confirmation link!",
    report_placeholder: "Suggest a better meaning or fix...",
    report_sent: "Feedback sent! Thank you.",
    fix_requested: "Fix Requested",
    admin_title: "Admin Reports",
    current_meaning: "Current Meaning",
    suggested_fix: "Suggested Fix",
    approve_fix: "Apply & Resolve",
    ignore_fix: "Ignore",
    no_reports: "No pending reports. Great job!",
    status_resolved: "Resolved",
    status_pending: "Pending",
    system_management: "System Management",
    report_issue: "Report",
    interface_language: "Interface Language",
    daily_streak: "Daily Streak",
    best_streak: "Best Streak",
    passes: "Passes",
    daily_streak_extended: "🎉 Congratulations! You've met your daily goal. Your streak is extended!",
    feedback_title: "Bug & Feedback",
    feedback_subtitle: "Help me improve the app",
    feedback_sent: "Message Received! Thanks!",
    feedback_placeholder_subject: "Subject...",
    feedback_placeholder_desc: "Describe the issue or idea...",
    feedback_btn_submit: "Submit Report",
    feedback_btn_sending: "Sending...",
    type_bug: "Bug",
    type_feedback: "Feedback",
    type_feature: "Feature",
    admin_user_stats: "User Stats",
    securing_session: "Securing Session...",
    mini_games: "Mini Games",
    final_streak: "Final Streak:",
  mode: "Mode",
  language: "Language",
  best: "Best",
  game_over: "Game Over",
  focus_swipe_game: "Focus Swipe Game",
  diff: "Diff",
  same: "Same",
  minigame_focus_best_30s: "30s Best",
  minigame_focus_best_60s: "60s Best",
  minigame_focus_best: "Best Score",
  minigame_focus_new_best: "✨ New Personal Best!",
  return_to_dashboard: "Return to Dashboard",
  words: "Words",
  dismiss_hint: "TAP BACKDROP OR [X] TO DISMISS",
  activity_log: "✨ Activity Log",
  progress_tracking: "Progress Tracking",
  last_14_days: "Last 14 Days of Study",
  total: "Total",
  reviews: "Reviews",
  average: "Average",
  daily: "Daily",
  motto_focus: "Focus",
  motto_consistency: "Consistency",
  motto_mastery: "Mastery",
  motto_footer: "Focus • Consistency • Mastery",
  daily_progress: "Daily Progress",
  ai_processing: "AI is Extracting & Translating...",
  status_online: "ONLINE",
  flip_control: "Flip",
    score_control: "Score",
    cards: "Cards",
    danger_zone: "Danger Zone",
  delete_account: "Delete Account",
  delete_account_desc: "Permanently remove your account and all data. This cannot be undone.",
  delete_confirm: "Are you absolutely sure? All your data will be wiped forever.",
  delete_btn: "Delete Forever",
  sfx_title: "Sound Effects",
    sfx_desc: "Play sound on pass/fail",
    swipe_only_title: "Swipe Only",
    swipe_only_desc: "Hide the Fail/Pass buttons, grade cards by swiping only",
    update_password: "Update Password",
    change_password: "Change Password",
    account_security: "Account Security",
    enter_new_password: "Enter your new credentials",
    confirm_to_update: "Confirm current password to update",
    social_managed: "Managed via Google/Facebook",
    set_new_creds: "Set your new security credentials",
    current_password_placeholder: "Current Password",
    new_password_placeholder: "New Password (min 6 chars)",
    save_password: "Save New Password",
    cancel_btn: "Cancel and Go Back",
    change_btn: "Change",
    back_home: "Back to Home",
    wrong_password: "Current password is incorrect.",
    password_updated_success: "Password updated successfully!",
    update_password_desc: "Change your login password to keep your account secure.",
    social_login_msg: "Your account is managed via Google/Facebook.",
    limit_reached_title: "DAILY LIMIT REACHED",
    limit_reached_msg: "You've added {{current}}/{{limit}} cards today. Come back tomorrow or upgrade to Premium for unlimited access!",
    partial_limit_msg: "Daily limit almost reached! Adding the first {{count}} words only.",
    upgrade_now: "UPGRADE TO PREMIUM",
    daily_usage: "Daily Usage",
    added_summary_limit: "Summary (Daily Limit Applied)",
    words_added: "Words Added",
    new_entries: "NEW ENTRIES PROCESSED",
    limit_notice: "DAILY LIMIT APPLIED",
    got_it: "Got it",
    study_kana: "Study Kana",
  },
  jp: {
    goal: "今日の目標",
    stats: "統計",
    fail: "わからない",
    pass: "わかった",
    fail_caps: "わからない",
    pass_caps: "わかった",
    already_know: "もう知っている",
    empty_deck: "デッキが空です",
    recall: "想起", 
    recognition: "認識", 
    mastery: "上達",
    tries: "試行数", 
    accuracy: "正解率",
    streak: "連続記録", // Renzoku kiroku (Continuous record)
    syncing_deck: "デッキを同期中...", // Dekki o dōkichū...
    days: "日", // Hi/Nichi
    back: "戻る",
    signout: "ログアウト", // Log-out (Standard katakana)
    active_collection: "現在のコレクション", // Genzai no korekushon (Current Collection)
    save: "保存する", // Hozon suru (To Save/Preserve)
    ai_add: "AI追加", // AI Tsuika
    batch_upload: "一括アップロード", // Ikkatsu Appurōdo
    audio_prefs: "音声設定", // Onsei Settei
    vocabulary: "語彙力", // Goiryoku (or simply ボキャブラリー)
    mastered: "習得済み", // Shūtoku-zumi (Completed/Learned)
    struggling: "要復習", // Yō-fukushū (Needs Review - sounds better than "failing")
    by_level: "レベル別語彙", // Reberu-betsu goi (Vocabulary by level)
    settings: "設定", // Settei
    close: "閉じる",
    close_settings: "設定を閉じる", // Settei o tojiru
    auto_play_jp: "日本語を自動再生", // Nihongo o jidō saisei
    auto_play_en: "英語を自動再生", // Eigo o jidō saisei
    starter_collections: "初級コレクション", // Shokyū korekushon (Beginner/Starter)
    available: "利用可能", // Riyō kanō (Standard "Available")
    audio_desc_jp: "カード表示時に漢字の音声を再生", // Card hyōji-ji ni kanji no onsei o saisei
    audio_desc_en: "カードをめくる時に英語の音声を再生", // Card o mekuru toki ni eigo no onsei o saisei
    process_text: "テキストを解析する", // Tekisuto o kaiseki suru (Analyze/Process Text)
    format_options: "入力形式の選択:", // Nyūryoku keishiki no sentaku (Choosing input format)
    format_list: "1. リスト形式: 単語, 意味 (1行に1項目)", // Risto keishiki: Tango, imi (1 item per line)
    format_lyrics: "2. 歌詞・長文: 歌詞や文章を貼り付けると、AIが新しい単語を抽出します！", // Kashi/Chōbun... (Paste lyrics/text and AI will extract words!)
    add_new_word: "単語を追加...", // Tango o tsuika
    success_added: "{{count}}語を追加しました！", // {{count}}-go o tsuika shimashita!
    in_a_row: "連続",           // Renzoku (Consecutive)
    loading: "読み込み中...",       // "Yomikomi-chū"
    loading_session: "セッションを読み込み中...", // Sesshon o yomikomi-chū
    daily_goal_met: "今日の目標達成！ 🎉",      // Kyō no mokuhyō tassei!
    start_journey: "カードを追加して、学習を始めましょう！", // Kādo o tsuika shite...
    get_started: "+ 学習を始める",                // Gakushū o hajimeru
    how_to_study: "学習方法",       // Gakushū hōhō
    forgot: "忘れた",               // Wasureta
    know_it: "覚えた！",            // Oboeta!
    swipe_to_start: "スワイプで開始", // Suwaipu de kaishi
    word_filters: "単語フィルター",              // Tango firutā
    search_placeholder: "漢字、読み、意味で検索...", // Kanji, yomi, imi de kensaku...
    app_language: "アプリの言語",               // Apuri no gengo
    app_language_desc: "英語と日本語を切り替えます", // Eigo to Nihongo o kirikaemasu
    kanji_reading: "漢字 / 読み",               // Kanji / Yomi
    english: "意味 (英語)",                     // Imi (Eigo) - "Meaning (English)"
    score: "スコア",                           // Sukoa
    action: "操作",                            // Sōsa (Operation/Action)
    add_word_to_block: "ブロックに単語を追加...", // Burokku ni tango o tsuika...
    added: "追加済み", // Tsuika-zumi (Status: Already added)
    free: "無料",     // Muryō (Price: Zero cost)
    looking_collections: "新しいコレクションを検索中...", // Atarashii korekushon o kensaku-chū...
    load_more: "さらに読み込む",       // Sarani yomikomu
    remaining: "残り",               // Nokori
    ai_building: "AIがカードを作成中...", // AI ga kādo o sakuseichū...
    delete: "削除",                 // Sakujo
    already_in_deck: "追加済み",       // Tsuika-zumi
    add_to_deck: "デッキに追加 +",    // Dekki ni tsuika +
    reset_password: "パスワードを再設定",
    create_account: "アカウント作成",
    welcome_message: "FlashKadoへようこそ！",
    email_placeholder: "メールアドレス",
    password_placeholder: "パスワード",
    processing: "処理中...",
    send_reset_link: "再設定リンクを送信",
    register_button: "登録する",
    login_button: "ログイン",
    or_continue_with: "または次で続行",
    switch_to_login: "すでにアカウントをお持ちですか？ログイン",
    switch_to_register: "初めての方はこちら。アカウント作成",
    back_to_login: "ログインに戻る",
    forgot_password_link: "パスワードをお忘れですか？",
    check_email_reset: "再設定リンクをメールで送信しました！",
    check_email_confirm: "確認リンクをメールで送信しました！",
    report_placeholder: "正しい意味や修正案を入力してください...",
    report_sent: "報告を送信しました。ありがとうございます！",
    fix_requested: "修正依頼",
    admin_title: "修正依頼一覧",
    current_meaning: "現在の意味",
    suggested_fix: "修正案",
    approve_fix: "反映して解決",
    ignore_fix: "無視する",
    no_reports: "保留中の依頼はありません。",
    status_resolved: "解決済み",
    status_pending: "保留中",
    system_management: "システム管理",
    report_issue: "報告",
    interface_language: "表示言語",
    daily_streak: "継続日数",
    best_streak: "最高連勝",
    passes: "連勝",
    daily_streak_extended: "🎉 おめでとう！今日の目標を達成しました。継続日数が更新されました！",
    feedback_title: "バグ報告・フィードバック",
    feedback_subtitle: "アプリの改善にご協力ください",
    feedback_sent: "送信完了しました。ありがとうございます！",
    feedback_placeholder_subject: "件名...",
    feedback_placeholder_desc: "問題点やアイデアを教えてください...",
    feedback_btn_submit: "レポートを送信",
    feedback_btn_sending: "送信中...",
    type_bug: "バグ",
    type_feedback: "意見",
    type_feature: "新機能",
    admin_user_stats: "ユーザー統計",
    securing_session: "セッションを保護中...",
    mini_games: "ミニゲーム",
    final_streak: "最終スコア:",
  mode: "モード",
  language: "言語",
  best: "自己ベスト",
  game_over: "ゲームオーバー",
  focus_swipe_game: "フォカス・スワイプ・ゲーム",
  diff: "違う",
  same: "同じ",
  minigame_focus_best_30s: "30秒ベスト",
  minigame_focus_best_60s: "60秒ベスト",
  minigame_focus_best: "自己ベスト",
  minigame_focus_new_best: "✨ 自己ベスト更新！",
  return_to_dashboard: "ダッシュボードに戻る",
  words: "単語",
  dismiss_hint: "枠外または[X]をタップして閉じる",
  activity_log: "✨ アクティビティログ",
  progress_tracking: "進捗状況の追跡",
  last_14_days: "過去14日間の学習履歴",
  total: "合計",
  reviews: "復習数",
  average: "平均",
  daily: "1日あたり",
  motto_focus: "集中",
  motto_consistency: "継続",
  motto_mastery: "習得",
  motto_footer: "集中 • 継続 • 習得",
  daily_progress: "今日の進捗",
  ai_processing: "AIが抽出・翻訳中...",
  status_online: "接続中",
  flip_control: "めくる",      // (Mekuru) To flip/turn over - very natural for cards
    score_control: "評価",      // (Hyouka) Evaluation/Grade - standard for SRS apps
    cards: "枚",
    danger_zone: "危険ゾーン",
  delete_account: "アカウント削除",
  delete_account_desc: "アカウントとすべてのデータを完全に削除します。この操作は取り消せません。",
  delete_confirm: "本当によろしいですか？すべてのデータが永久に削除されます。",
  delete_btn: "永久に削除する",
  sfx_title: "効果音",
    sfx_desc: "正解・不正解時に音を鳴らす",
    swipe_only_title: "スワイプのみ",
    swipe_only_desc: "「わかった」「わからない」ボタンを隠し、スワイプのみで判定する",
    update_password: "パスワード更新",
    change_password: "パスワード変更",
    account_security: "アカウントセキュリティ",
    enter_new_password: "新しいパスワードを入力してください",
    confirm_to_update: "現在のパスワードを入力して更新",
    social_managed: "Google/Facebookで管理されています",
    set_new_creds: "新しいセキュリティ設定を行ってください",
    current_password_placeholder: "現在のパスワード",
    new_password_placeholder: "新しいパスワード（6文字以上）",
    save_password: "パスワードを保存",
    cancel_btn: "キャンセルして戻る",
    change_btn: "変更する",
    back_home: "ホームに戻る",
    wrong_password: "現在のパスワードが正しくありません。",
    password_updated_success: "パスワードを更新しました！",
    update_password_desc: "セキュリティ向上のため、ログインパスワードを変更します。",
    social_login_msg: "このアカウントはGoogle/Facebookで管理されています。",
    limit_reached_title: "一日の上限に達しました",
    limit_reached_msg: "本日は {{current}}/{{limit}} 枚のカードを追加しました。明日また戻ってくるか、プレミアムにアップグレードして無制限に利用しましょう！",
    partial_limit_msg: "一日の上限に近いいため、最初の {{count}} 語のみを追加します。",
    upgrade_now: "プレミアムに移行",
    daily_usage: "今日の使用量",
    added_summary_limit: "追加済みリスト（一日の上限適用）",
    words_added: "追加済み単語",
    new_entries: "個の新規エントリを処理しました",
    limit_notice: "一日の上限適用済み",
    got_it: "了解",
    study_kana: "仮名学習",
  }
};