-- contextNote was generated by the AI card-generation prompt but never read
-- or displayed anywhere in the app — pure dead data, and paying Gemini
-- output tokens for it on every card was wasted cost. Prompt no longer
-- asks for it; dropping the column since nothing references it.
ALTER TABLE master_cards DROP COLUMN IF EXISTS "contextNote";
